apiVersion: v1
kind: Service
metadata:
  name: authapp-service
  labels: 
    app: authapp
spec : 
  type: NodePort
  selector:
    app: authapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30200